server:
  port: 8085
wechat:
  appId: 'wx9840dfe69789d1d0'
  secret: '08e1e853f72cc57d1b1cccfbe19be3c9'
  userId: 'oph2P6CIwivsKphnXw5OyXPa_Lco'
  templateId: 'sakRNj4mUabVpL4d5-IQXxmZG_TKjPZGmriAg-uwMWA'
  district_id: '321281'
  ak: 'OlThi7uaq9VqaE1KAE7QEnQsNY5uMRwK'
  loveDate: '2021-10-16'
  birthday: '2001-04-14'
  rainbowKey: '173f6e2411018023decccd230e3cd4fa'


knife4j:
  enable: true

# 日志
logging:
  file:
    path: D:/xjaxl